all: test1 test2 test3 test4 test5

test1:
	gcc -o test1 test1.c
test2:
	gcc -o test2 test2.c
test3:
	gcc -o test3 test3.c
test4:
	gcc -o test4 test4.c
test5:
	gcc -o test5 test5.c
clean:
	rm test1 test2 test3 test4 test5
